# Generated by Django 3.2.6 on 2021-08-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(help_text='Blog Image', null=True, upload_to='blog_post/', verbose_name='Blog Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Enter your blog title here.', max_length=200, null=True, unique=True, verbose_name='Blog Title'),
        ),
    ]
