# Generated by Django 3.2.6 on 2021-09-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(help_text='the order id', max_length=200, null=True, verbose_name='orderID')),
                ('billingname', models.CharField(help_text='Enter your blog title here.', max_length=200, null=True, verbose_name='Billing Name')),
                ('date', models.DateTimeField(help_text='The date of the order.', null=True, verbose_name='date')),
                ('total', models.FloatField(null=True, verbose_name='total')),
                ('paymentstatus', models.BooleanField()),
            ],
        ),
    ]
